"""Static word lists for the deterministic mapping tasks.

Each list is (input, output). Inputs are unique within a list. Lists are kept in
source form (rather than generated) so that every item is inspectable.
"""

ANTONYM: list[tuple[str, str]] = [
    ("hot", "cold"), ("big", "small"), ("up", "down"), ("fast", "slow"), ("happy", "sad"),
    ("light", "dark"), ("tall", "short"), ("rich", "poor"), ("young", "old"), ("wet", "dry"),
    ("hard", "soft"), ("strong", "weak"), ("early", "late"), ("open", "closed"), ("full", "empty"),
    ("heavy", "light"), ("high", "low"), ("long", "short"), ("wide", "narrow"), ("thick", "thin"),
    ("clean", "dirty"), ("loud", "quiet"), ("sweet", "sour"), ("true", "false"), ("good", "bad"),
    ("right", "wrong"), ("left", "right"), ("day", "night"), ("in", "out"), ("on", "off"),
    ("above", "below"), ("before", "after"), ("inside", "outside"), ("near", "far"), ("push", "pull"),
    ("buy", "sell"), ("give", "take"), ("win", "lose"), ("start", "stop"), ("begin", "end"),
    ("love", "hate"), ("friend", "enemy"), ("question", "answer"), ("black", "white"), ("north", "south"),
    ("east", "west"), ("summer", "winter"), ("male", "female"), ("boy", "girl"), ("man", "woman"),
    ("king", "queen"), ("husband", "wife"), ("brother", "sister"), ("father", "mother"), ("son", "daughter"),
    ("first", "last"), ("top", "bottom"), ("front", "back"), ("always", "never"), ("more", "less"),
    ("many", "few"), ("all", "none"), ("same", "different"), ("alive", "dead"), ("asleep", "awake"),
    ("cheap", "expensive"), ("brave", "cowardly"), ("kind", "cruel"), ("polite", "rude"), ("wise", "foolish"),
    ("smart", "stupid"), ("beautiful", "ugly"), ("safe", "dangerous"), ("simple", "complex"), ("easy", "difficult"),
    ("thin", "fat"), ("sharp", "dull"), ("smooth", "rough"), ("bright", "dim"), ("noisy", "silent"),
    ("wild", "tame"), ("public", "private"), ("major", "minor"), ("maximum", "minimum"), ("include", "exclude"),
    ("increase", "decrease"), ("expand", "contract"), ("accept", "reject"), ("arrive", "depart"), ("enter", "exit"),
    ("attack", "defend"), ("create", "destroy"), ("build", "demolish"), ("remember", "forget"), ("laugh", "cry"),
    ("lead", "follow"), ("teach", "learn"), ("lend", "borrow"), ("import", "export"), ("float", "sink"),
    ("rise", "fall"), ("appear", "disappear"), ("connect", "disconnect"), ("agree", "disagree"), ("approve", "disapprove"),
    ("obey", "disobey"), ("lock", "unlock"), ("tie", "untie"), ("dress", "undress"), ("wrap", "unwrap"),
    ("visible", "invisible"), ("possible", "impossible"), ("legal", "illegal"), ("regular", "irregular"), ("mature", "immature"),
    ("honest", "dishonest"), ("loyal", "disloyal"), ("patient", "impatient"), ("perfect", "imperfect"), ("known", "unknown"),
    ("fair", "unfair"), ("able", "unable"), ("happy", "unhappy"),  # duplicate input removed below
    ("lucky", "unlucky"), ("usual", "unusual"), ("certain", "uncertain"), ("common", "rare"), ("guilty", "innocent"),
    ("ancient", "modern"), ("permanent", "temporary"), ("horizontal", "vertical"), ("optimist", "pessimist"), ("victory", "defeat"),
    ("success", "failure"), ("profit", "loss"), ("wealth", "poverty"), ("peace", "war"), ("heaven", "hell"),
    ("birth", "death"), ("entrance", "exit"), ("arrival", "departure"), ("ceiling", "floor"), ("sunrise", "sunset"),
    ("beginning", "end"), ("maximum", "minimum"),  # duplicate input removed below
    ("plus", "minus"), ("add", "subtract"), ("multiply", "divide"), ("odd", "even"), ("positive", "negative"),
    ("liquid", "solid"), ("fresh", "stale"), ("raw", "cooked"), ("ripe", "unripe"), ("straight", "crooked"),
    ("tight", "loose"), ("deep", "shallow"), ("steep", "gentle"), ("calm", "stormy"), ("cloudy", "sunny"),
    ("warm", "cool"), ("freeze", "melt"), ("boil", "freeze"), ("healthy", "sick"), ("strength", "weakness"),
    ("giant", "dwarf"), ("hero", "villain"), ("master", "servant"), ("teacher", "student"), ("doctor", "patient"),
    ("predator", "prey"), ("host", "guest"), ("buyer", "seller"), ("landlord", "tenant"), ("employer", "employee"),
    ("majority", "minority"), ("ancestor", "descendant"), ("amateur", "professional"), ("urban", "rural"), ("domestic", "foreign"),
    ("natural", "artificial"), ("generous", "stingy"), ("humble", "proud"), ("cautious", "reckless"), ("famous", "obscure"),
    ("absent", "present"), ("abundant", "scarce"), ("active", "passive"), ("advance", "retreat"), ("ally", "enemy"),
    ("ascend", "descend"), ("bless", "curse"), ("bold", "timid"), ("broad", "narrow"), ("careful", "careless"),
    ("compliment", "insult"), ("conceal", "reveal"), ("confirm", "deny"), ("courage", "fear"), ("dawn", "dusk"),
    ("encourage", "discourage"), ("exterior", "interior"), ("forward", "backward"), ("frequent", "rare"), ("gentle", "harsh"),
    ("hungry", "full"), ("innocent", "guilty"), ("junior", "senior"), ("knowledge", "ignorance"), ("lazy", "diligent"),
    ("literal", "figurative"), ("loose", "tight"), ("mild", "severe"), ("noon", "midnight"), ("obvious", "hidden"),
    ("optional", "mandatory"), ("order", "chaos"), ("plural", "singular"), ("praise", "criticism"), ("primary", "secondary"),
    ("quick", "slow"), ("reward", "punishment"), ("rough", "smooth"), ("scatter", "gather"), ("shrink", "grow"),
    ("sober", "drunk"), ("sour", "sweet"), ("spend", "save"), ("stiff", "flexible"), ("tragedy", "comedy"),
    ("transparent", "opaque"), ("unite", "divide"), ("vacant", "occupied"), ("vague", "clear"), ("victory", "defeat"),
    ("voluntary", "compulsory"), ("wax", "wane"), ("whisper", "shout"), ("zenith", "nadir"), ("virtue", "vice"),
]

PLURAL: list[tuple[str, str]] = [
    ("cat", "cats"), ("dog", "dogs"), ("house", "houses"), ("car", "cars"), ("tree", "trees"),
    ("book", "books"), ("child", "children"), ("man", "men"), ("woman", "women"), ("mouse", "mice"),
    ("foot", "feet"), ("tooth", "teeth"), ("goose", "geese"), ("person", "people"), ("ox", "oxen"),
    ("box", "boxes"), ("bus", "buses"), ("church", "churches"), ("dish", "dishes"), ("glass", "glasses"),
    ("city", "cities"), ("baby", "babies"), ("story", "stories"), ("party", "parties"), ("country", "countries"),
    ("leaf", "leaves"), ("knife", "knives"), ("wife", "wives"), ("life", "lives"), ("wolf", "wolves"),
    ("half", "halves"), ("shelf", "shelves"), ("calf", "calves"), ("loaf", "loaves"), ("thief", "thieves"),
    ("potato", "potatoes"), ("tomato", "tomatoes"), ("hero", "heroes"), ("echo", "echoes"), ("piano", "pianos"),
    ("photo", "photos"), ("radio", "radios"), ("zoo", "zoos"), ("video", "videos"), ("kilo", "kilos"),
    ("apple", "apples"), ("banana", "bananas"), ("orange", "oranges"), ("grape", "grapes"), ("lemon", "lemons"),
    ("chair", "chairs"), ("table", "tables"), ("window", "windows"), ("door", "doors"), ("wall", "walls"),
    ("bird", "birds"), ("fish", "fish"), ("sheep", "sheep"), ("deer", "deer"), ("horse", "horses"),
    ("cow", "cows"), ("pig", "pigs"), ("duck", "ducks"), ("chicken", "chickens"), ("rabbit", "rabbits"),
    ("lion", "lions"), ("tiger", "tigers"), ("bear", "bears"), ("monkey", "monkeys"), ("elephant", "elephants"),
    ("flower", "flowers"), ("river", "rivers"), ("mountain", "mountains"), ("lake", "lakes"), ("ocean", "oceans"),
    ("cloud", "clouds"), ("star", "stars"), ("planet", "planets"), ("rock", "rocks"), ("stone", "stones"),
    ("hand", "hands"), ("eye", "eyes"), ("ear", "ears"), ("finger", "fingers"), ("leg", "legs"),
    ("arm", "arms"), ("head", "heads"), ("heart", "hearts"), ("bone", "bones"), ("nose", "noses"),
    ("shoe", "shoes"), ("hat", "hats"), ("shirt", "shirts"), ("dress", "dresses"), ("coat", "coats"),
    ("cup", "cups"), ("plate", "plates"), ("fork", "forks"), ("spoon", "spoons"), ("bottle", "bottles"),
    ("pen", "pens"), ("pencil", "pencils"), ("page", "pages"), ("letter", "letters"), ("word", "words"),
    ("school", "schools"), ("teacher", "teachers"), ("student", "students"), ("class", "classes"), ("lesson", "lessons"),
    ("boy", "boys"), ("girl", "girls"), ("friend", "friends"), ("family", "families"), ("brother", "brothers"),
    ("king", "kings"), ("queen", "queens"), ("prince", "princes"), ("princess", "princesses"), ("castle", "castles"),
    ("ship", "ships"), ("boat", "boats"), ("train", "trains"), ("plane", "planes"), ("bicycle", "bicycles"),
    ("road", "roads"), ("street", "streets"), ("bridge", "bridges"), ("tower", "towers"), ("garden", "gardens"),
    ("watch", "watches"), ("brush", "brushes"), ("match", "matches"), ("fox", "foxes"), ("tax", "taxes"),
    ("wish", "wishes"), ("beach", "beaches"), ("peach", "peaches"), ("bench", "benches"), ("branch", "branches"),
    ("lady", "ladies"), ("fly", "flies"), ("sky", "skies"), ("cherry", "cherries"), ("berry", "berries"),
    ("puppy", "puppies"), ("pony", "ponies"), ("body", "bodies"), ("copy", "copies"), ("library", "libraries"),
    ("key", "keys"), ("day", "days"), ("toy", "toys"), ("valley", "valleys"), ("donkey", "donkeys"),
    ("wife", "wives"),  # duplicate input removed below
    ("elf", "elves"), ("self", "selves"), ("scarf", "scarves"), ("roof", "roofs"), ("chef", "chefs"),
    ("cliff", "cliffs"), ("belief", "beliefs"), ("chief", "chiefs"), ("cactus", "cacti"), ("fungus", "fungi"),
    ("nucleus", "nuclei"), ("crisis", "crises"), ("analysis", "analyses"), ("thesis", "theses"), ("basis", "bases"),
    ("phenomenon", "phenomena"), ("criterion", "criteria"), ("datum", "data"), ("medium", "media"), ("bacterium", "bacteria"),
    ("louse", "lice"), ("moose", "moose"), ("salmon", "salmon"), ("trout", "trout"), ("aircraft", "aircraft"),
    ("computer", "computers"), ("phone", "phones"), ("screen", "screens"), ("camera", "cameras"), ("machine", "machines"),
    ("song", "songs"), ("game", "games"), ("movie", "movies"), ("picture", "pictures"), ("painting", "paintings"),
    ("idea", "ideas"), ("dream", "dreams"), ("problem", "problems"), ("answer", "answers"), ("question", "questions"),
    ("minute", "minutes"), ("hour", "hours"), ("week", "weeks"), ("month", "months"), ("year", "years"),
    ("coin", "coins"), ("dollar", "dollars"), ("price", "prices"), ("shop", "shops"), ("market", "markets"),
    ("egg", "eggs"), ("cake", "cakes"), ("cookie", "cookies"), ("sandwich", "sandwiches"), ("pizza", "pizzas"),
    ("bag", "bags"), ("basket", "baskets"), ("bucket", "buckets"), ("candle", "candles"), ("blanket", "blankets"),
    ("island", "islands"), ("forest", "forests"), ("desert", "deserts"), ("field", "fields"), ("farm", "farms"),
    ("nurse", "nurses"), ("doctor", "doctors"), ("lawyer", "lawyers"), ("actor", "actors"), ("artist", "artists"),
    ("wolf", "wolves"),  # duplicate input removed below
    ("goat", "goats"), ("snake", "snakes"), ("frog", "frogs"), ("spider", "spiders"), ("bee", "bees"),
    ("ant", "ants"), ("worm", "worms"), ("whale", "whales"), ("shark", "sharks"), ("dolphin", "dolphins"),
]

PAST_TENSE: list[tuple[str, str]] = [
    ("walk", "walked"), ("talk", "talked"), ("jump", "jumped"), ("play", "played"), ("work", "worked"),
    ("go", "went"), ("see", "saw"), ("eat", "ate"), ("drink", "drank"), ("run", "ran"),
    ("come", "came"), ("take", "took"), ("give", "gave"), ("make", "made"), ("know", "knew"),
    ("think", "thought"), ("bring", "brought"), ("buy", "bought"), ("catch", "caught"), ("teach", "taught"),
    ("fight", "fought"), ("seek", "sought"), ("sing", "sang"), ("ring", "rang"), ("swim", "swam"),
    ("begin", "began"), ("sit", "sat"), ("stand", "stood"), ("understand", "understood"), ("write", "wrote"),
    ("ride", "rode"), ("drive", "drove"), ("rise", "rose"), ("speak", "spoke"), ("break", "broke"),
    ("choose", "chose"), ("freeze", "froze"), ("steal", "stole"), ("wake", "woke"), ("wear", "wore"),
    ("tear", "tore"), ("swear", "swore"), ("bear", "bore"), ("fly", "flew"), ("grow", "grew"),
    ("throw", "threw"), ("blow", "blew"), ("draw", "drew"), ("fall", "fell"), ("hold", "held"),
    ("tell", "told"), ("sell", "sold"), ("feel", "felt"), ("keep", "kept"), ("sleep", "slept"),
    ("sweep", "swept"), ("weep", "wept"), ("meet", "met"), ("feed", "fed"), ("lead", "led"),
    ("read", "read"), ("leave", "left"), ("lose", "lost"), ("find", "found"), ("bind", "bound"),
    ("wind", "wound"), ("grind", "ground"), ("have", "had"), ("say", "said"), ("pay", "paid"),
    ("lay", "laid"), ("hear", "heard"), ("build", "built"), ("send", "sent"), ("spend", "spent"),
    ("lend", "lent"), ("bend", "bent"), ("mean", "meant"), ("deal", "dealt"), ("dig", "dug"),
    ("stick", "stuck"), ("strike", "struck"), ("hang", "hung"), ("win", "won"), ("shine", "shone"),
    ("shoot", "shot"), ("get", "got"), ("forget", "forgot"), ("sink", "sank"), ("shrink", "shrank"),
    ("spring", "sprang"), ("stink", "stank"), ("bite", "bit"), ("hide", "hid"), ("slide", "slid"),
    ("light", "lit"), ("do", "did"), ("bleed", "bled"), ("breed", "bred"), ("flee", "fled"),
    ("cook", "cooked"), ("look", "looked"), ("help", "helped"), ("call", "called"), ("ask", "asked"),
    ("want", "wanted"), ("need", "needed"), ("start", "started"), ("wait", "waited"), ("visit", "visited"),
    ("open", "opened"), ("close", "closed"), ("live", "lived"), ("love", "loved"), ("hope", "hoped"),
    ("use", "used"), ("move", "moved"), ("save", "saved"), ("smile", "smiled"), ("dance", "danced"),
    ("stop", "stopped"), ("plan", "planned"), ("drop", "dropped"), ("shop", "shopped"), ("hug", "hugged"),
    ("rub", "rubbed"), ("beg", "begged"), ("clap", "clapped"), ("grab", "grabbed"), ("chat", "chatted"),
    ("cry", "cried"), ("try", "tried"), ("carry", "carried"), ("study", "studied"), ("hurry", "hurried"),
    ("worry", "worried"), ("marry", "married"), ("copy", "copied"), ("bury", "buried"), ("deny", "denied"),
    ("enjoy", "enjoyed"), ("stay", "stayed"), ("pray", "prayed"), ("obey", "obeyed"), ("delay", "delayed"),
    ("climb", "climbed"), ("clean", "cleaned"), ("cross", "crossed"), ("dream", "dreamed"), ("end", "ended"),
    ("fix", "fixed"), ("fill", "filled"), ("follow", "followed"), ("guess", "guessed"), ("hunt", "hunted"),
    ("join", "joined"), ("kick", "kicked"), ("kill", "killed"), ("kiss", "kissed"), ("laugh", "laughed"),
    ("learn", "learned"), ("listen", "listened"), ("lock", "locked"), ("mark", "marked"), ("miss", "missed"),
    ("paint", "painted"), ("pass", "passed"), ("pick", "picked"), ("pull", "pulled"), ("push", "pushed"),
    ("rain", "rained"), ("reach", "reached"), ("rest", "rested"), ("return", "returned"), ("roll", "rolled"),
    ("shout", "shouted"), ("show", "showed"), ("sign", "signed"), ("smell", "smelled"), ("snow", "snowed"),
    ("stamp", "stamped"), ("touch", "touched"), ("turn", "turned"), ("wash", "washed"), ("watch", "watched"),
    ("wish", "wished"), ("yell", "yelled"), ("bake", "baked"), ("change", "changed"), ("decide", "decided"),
    ("arrive", "arrived"), ("agree", "agreed"), ("believe", "believed"), ("share", "shared"), ("taste", "tasted"),
    ("cut", "cut"), ("put", "put"), ("hit", "hit"), ("let", "let"), ("set", "set"),
    ("shut", "shut"), ("hurt", "hurt"), ("cost", "cost"), ("spread", "spread"), ("burst", "burst"),
    ("become", "became"), ("forgive", "forgave"), ("overcome", "overcame"), ("withdraw", "withdrew"), ("undertake", "undertook"),
    ("wring", "wrung"), ("cling", "clung"), ("fling", "flung"), ("sting", "stung"), ("swing", "swung"),
    ("spin", "spun"), ("spit", "spat"), ("tread", "trod"), ("weave", "wove"), ("strive", "strove"),
    ("arise", "arose"), ("awake", "awoke"), ("forbid", "forbade"), ("mistake", "mistook"), ("shake", "shook"),
]

EN_FR: list[tuple[str, str]] = [
    ("dog", "chien"), ("cat", "chat"), ("house", "maison"), ("water", "eau"), ("bread", "pain"),
    ("book", "livre"), ("car", "voiture"), ("tree", "arbre"), ("sun", "soleil"), ("moon", "lune"),
    ("red", "rouge"), ("blue", "bleu"), ("green", "vert"), ("black", "noir"), ("white", "blanc"),
    ("yellow", "jaune"), ("one", "un"), ("two", "deux"), ("three", "trois"), ("four", "quatre"),
    ("five", "cinq"), ("six", "six"), ("seven", "sept"), ("eight", "huit"), ("nine", "neuf"),
    ("ten", "dix"), ("man", "homme"), ("woman", "femme"), ("boy", "garçon"), ("girl", "fille"),
    ("child", "enfant"), ("friend", "ami"), ("brother", "frère"), ("sister", "sœur"), ("father", "père"),
    ("mother", "mère"), ("king", "roi"), ("queen", "reine"), ("city", "ville"), ("country", "pays"),
    ("world", "monde"), ("day", "jour"), ("night", "nuit"), ("morning", "matin"), ("evening", "soir"),
    ("week", "semaine"), ("month", "mois"), ("year", "année"), ("time", "temps"), ("hour", "heure"),
    ("milk", "lait"), ("cheese", "fromage"), ("apple", "pomme"), ("wine", "vin"), ("meat", "viande"),
    ("fish", "poisson"), ("egg", "œuf"), ("salt", "sel"), ("sugar", "sucre"), ("butter", "beurre"),
    ("table", "table"), ("chair", "chaise"), ("door", "porte"), ("window", "fenêtre"), ("bed", "lit"),
    ("kitchen", "cuisine"), ("room", "chambre"), ("garden", "jardin"), ("street", "rue"), ("bridge", "pont"),
    ("school", "école"), ("teacher", "professeur"), ("student", "étudiant"), ("church", "église"), ("castle", "château"),
    ("hand", "main"), ("head", "tête"), ("eye", "œil"), ("mouth", "bouche"), ("nose", "nez"),
    ("foot", "pied"), ("arm", "bras"), ("heart", "cœur"), ("hair", "cheveux"), ("tooth", "dent"),
    ("horse", "cheval"), ("bird", "oiseau"), ("cow", "vache"), ("pig", "cochon"), ("sheep", "mouton"),
    ("mouse", "souris"), ("rabbit", "lapin"), ("wolf", "loup"), ("bear", "ours"), ("lion", "lion"),
    ("flower", "fleur"), ("river", "rivière"), ("mountain", "montagne"), ("sea", "mer"), ("forest", "forêt"),
    ("sky", "ciel"), ("star", "étoile"), ("rain", "pluie"), ("snow", "neige"), ("wind", "vent"),
    ("fire", "feu"), ("earth", "terre"), ("stone", "pierre"), ("gold", "or"), ("silver", "argent"),
    ("love", "amour"), ("life", "vie"), ("death", "mort"), ("war", "guerre"), ("peace", "paix"),
    ("truth", "vérité"), ("dream", "rêve"), ("song", "chanson"), ("word", "mot"), ("name", "nom"),
    ("hat", "chapeau"), ("shoe", "chaussure"), ("shirt", "chemise"), ("dress", "robe"), ("coat", "manteau"),
    ("key", "clé"), ("money", "argent"), ("letter", "lettre"), ("paper", "papier"), ("pen", "stylo"),
    ("cold", "froid"), ("hot", "chaud"), ("big", "grand"), ("small", "petit"), ("new", "nouveau"),
    ("old", "vieux"), ("young", "jeune"), ("good", "bon"), ("bad", "mauvais"), ("beautiful", "beau"),
    ("happy", "heureux"), ("sad", "triste"), ("strong", "fort"), ("weak", "faible"), ("rich", "riche"),
    ("poor", "pauvre"), ("fast", "rapide"), ("slow", "lent"), ("long", "long"), ("short", "court"),
    ("yes", "oui"), ("no", "non"), ("thank you", "merci"), ("hello", "bonjour"), ("goodbye", "au revoir"),
    ("please", "s'il vous plaît"), ("today", "aujourd'hui"), ("tomorrow", "demain"), ("yesterday", "hier"), ("now", "maintenant"),
    ("always", "toujours"), ("never", "jamais"), ("here", "ici"), ("there", "là"), ("where", "où"),
    ("who", "qui"), ("what", "quoi"), ("why", "pourquoi"), ("how", "comment"), ("when", "quand"),
    ("to eat", "manger"), ("to drink", "boire"), ("to sleep", "dormir"), ("to speak", "parler"), ("to read", "lire"),
    ("to write", "écrire"), ("to run", "courir"), ("to walk", "marcher"), ("to see", "voir"), ("to know", "savoir"),
    ("to want", "vouloir"), ("to come", "venir"), ("to go", "aller"), ("to give", "donner"), ("to take", "prendre"),
    ("to love", "aimer"), ("to sing", "chanter"), ("to dance", "danser"), ("to play", "jouer"), ("to work", "travailler"),
    ("to open", "ouvrir"), ("to close", "fermer"), ("to buy", "acheter"), ("to sell", "vendre"), ("to learn", "apprendre"),
    ("summer", "été"), ("winter", "hiver"), ("spring", "printemps"), ("autumn", "automne"), ("holiday", "vacances"),
    ("monday", "lundi"), ("tuesday", "mardi"), ("wednesday", "mercredi"), ("thursday", "jeudi"), ("friday", "vendredi"),
    ("saturday", "samedi"), ("sunday", "dimanche"), ("january", "janvier"), ("february", "février"), ("march", "mars"),
    ("april", "avril"), ("may", "mai"), ("june", "juin"), ("july", "juillet"), ("august", "août"),
    ("september", "septembre"), ("october", "octobre"), ("november", "novembre"), ("december", "décembre"), ("hundred", "cent"),
    ("thousand", "mille"), ("boat", "bateau"), ("train", "train"), ("plane", "avion"), ("bicycle", "vélo"),
    ("road", "route"), ("shop", "magasin"), ("market", "marché"), ("bank", "banque"), ("hospital", "hôpital"),
    ("doctor", "médecin"), ("nurse", "infirmière"), ("police", "police"), ("soldier", "soldat"), ("farmer", "fermier"),
    ("cake", "gâteau"), ("soup", "soupe"), ("rice", "riz"), ("potato", "pomme de terre"), ("carrot", "carotte"),
    ("onion", "oignon"), ("garlic", "ail"), ("orange", "orange"), ("strawberry", "fraise"), ("lemon", "citron"),
    ("cup", "tasse"), ("glass", "verre"), ("plate", "assiette"), ("knife", "couteau"), ("fork", "fourchette"),
    ("spoon", "cuillère"), ("bottle", "bouteille"), ("bag", "sac"), ("box", "boîte"), ("gift", "cadeau"),
    ("game", "jeu"), ("ball", "ballon"), ("toy", "jouet"), ("picture", "image"), ("music", "musique"),
    ("light", "lumière"), ("shadow", "ombre"), ("island", "île"), ("beach", "plage"), ("lake", "lac"),
    ("dog", "chien"),  # duplicate input removed below
]


def dedupe(pairs: list[tuple[str, str]]) -> list[tuple[str, str]]:
    """Keep the first occurrence of each input (stable order)."""
    seen: set[str] = set()
    out: list[tuple[str, str]] = []
    for i, o in pairs:
        if i in seen:
            continue
        seen.add(i)
        out.append((i, o))
    return out
