"""Extensions of the word lists (added so a 192-example evaluation pool fits).

Merged into the base lists by ``data.py``; see ``docs/DECISIONS.md`` (D14).
"""

ANTONYM_EXTRA: list[tuple[str, str]] = [
    ("cold", "hot"), ("small", "big"), ("down", "up"), ("slow", "fast"), ("sad", "happy"),
    ("dark", "light"), ("short", "tall"), ("poor", "rich"), ("old", "young"), ("dry", "wet"),
    ("soft", "hard"), ("weak", "strong"), ("late", "early"), ("closed", "open"), ("empty", "full"),
    ("low", "high"), ("narrow", "wide"), ("dirty", "clean"), ("quiet", "loud"), ("false", "true"),
    ("bad", "good"), ("wrong", "right"), ("night", "day"), ("out", "in"), ("off", "on"),
    ("below", "above"), ("after", "before"), ("outside", "inside"), ("far", "near"), ("pull", "push"),
    ("sell", "buy"), ("take", "give"), ("lose", "win"), ("stop", "start"), ("end", "begin"),
    ("hate", "love"), ("enemy", "friend"), ("answer", "question"), ("white", "black"), ("south", "north"),
    ("west", "east"), ("winter", "summer"), ("female", "male"), ("girl", "boy"), ("woman", "man"),
    ("queen", "king"), ("wife", "husband"), ("sister", "brother"), ("mother", "father"), ("daughter", "son"),
    ("last", "first"), ("bottom", "top"), ("back", "front"), ("never", "always"), ("less", "more"),
    ("few", "many"), ("none", "all"), ("different", "same"), ("dead", "alive"), ("awake", "asleep"),
    ("expensive", "cheap"), ("cruel", "kind"), ("rude", "polite"), ("ugly", "beautiful"), ("dangerous", "safe"),
    ("difficult", "easy"), ("fat", "thin"), ("dull", "sharp"), ("dim", "bright"), ("silent", "noisy"),
    ("tame", "wild"), ("private", "public"), ("minor", "major"), ("minimum", "maximum"), ("exclude", "include"),
    ("decrease", "increase"), ("reject", "accept"), ("depart", "arrive"), ("exit", "enter"), ("defend", "attack"),
    ("destroy", "create"), ("demolish", "build"), ("forget", "remember"), ("cry", "laugh"), ("follow", "lead"),
    ("learn", "teach"), ("borrow", "lend"), ("export", "import"), ("sink", "float"), ("fall", "rise"),
    ("disappear", "appear"), ("disconnect", "connect"), ("disagree", "agree"), ("unlock", "lock"), ("invisible", "visible"),
    ("impossible", "possible"), ("illegal", "legal"), ("irregular", "regular"), ("dishonest", "honest"), ("impatient", "patient"),
    ("unknown", "known"), ("unfair", "fair"), ("unable", "able"), ("unlucky", "lucky"), ("uncertain", "certain"),
    ("rare", "common"), ("modern", "ancient"), ("temporary", "permanent"), ("vertical", "horizontal"), ("pessimist", "optimist"),
    ("defeat", "victory"), ("failure", "success"), ("loss", "profit"), ("poverty", "wealth"), ("war", "peace"),
    ("hell", "heaven"), ("death", "birth"), ("departure", "arrival"), ("floor", "ceiling"), ("sunset", "sunrise"),
    ("minus", "plus"), ("subtract", "add"), ("divide", "multiply"), ("even", "odd"), ("negative", "positive"),
    ("solid", "liquid"), ("stale", "fresh"), ("cooked", "raw"), ("crooked", "straight"), ("shallow", "deep"),
    ("stormy", "calm"), ("sunny", "cloudy"), ("cool", "warm"), ("melt", "freeze"), ("sick", "healthy"),
    ("weakness", "strength"), ("dwarf", "giant"), ("villain", "hero"), ("servant", "master"), ("student", "teacher"),
    ("prey", "predator"), ("guest", "host"), ("seller", "buyer"), ("tenant", "landlord"), ("employee", "employer"),
    ("minority", "majority"), ("descendant", "ancestor"), ("professional", "amateur"), ("rural", "urban"), ("foreign", "domestic"),
    ("artificial", "natural"), ("stingy", "generous"), ("proud", "humble"), ("reckless", "cautious"), ("present", "absent"),
    ("scarce", "abundant"), ("passive", "active"), ("retreat", "advance"), ("descend", "ascend"), ("curse", "bless"),
    ("timid", "bold"), ("careless", "careful"), ("insult", "compliment"), ("reveal", "conceal"), ("deny", "confirm"),
    ("fear", "courage"), ("dusk", "dawn"), ("discourage", "encourage"), ("interior", "exterior"), ("backward", "forward"),
    ("harsh", "gentle"), ("senior", "junior"), ("ignorance", "knowledge"), ("diligent", "lazy"), ("figurative", "literal"),
    ("severe", "mild"), ("midnight", "noon"), ("hidden", "obvious"), ("mandatory", "optional"), ("chaos", "order"),
    ("singular", "plural"), ("criticism", "praise"), ("secondary", "primary"), ("punishment", "reward"), ("gather", "scatter"),
    ("grow", "shrink"), ("drunk", "sober"), ("save", "spend"), ("flexible", "stiff"), ("comedy", "tragedy"),
    ("opaque", "transparent"), ("occupied", "vacant"), ("clear", "vague"), ("compulsory", "voluntary"), ("wane", "wax"),
    ("shout", "whisper"), ("nadir", "zenith"), ("vice", "virtue"),
]

PLURAL_EXTRA: list[tuple[str, str]] = [
    ("lamp", "lamps"), ("sofa", "sofas"), ("mirror", "mirrors"), ("carpet", "carpets"), ("pillow", "pillows"),
    ("curtain", "curtains"), ("ladder", "ladders"), ("hammer", "hammers"), ("nail", "nails"), ("screw", "screws"),
    ("rope", "ropes"), ("wheel", "wheels"), ("engine", "engines"), ("ticket", "tickets"), ("wallet", "wallets"),
    ("button", "buttons"), ("pocket", "pockets"), ("ribbon", "ribbons"), ("needle", "needles"), ("thread", "threads"),
    ("jacket", "jackets"), ("glove", "gloves"), ("sock", "socks"), ("boot", "boots"), ("sandal", "sandals"),
    ("helmet", "helmets"), ("crown", "crowns"), ("sword", "swords"), ("shield", "shields"), ("arrow", "arrows"),
    ("cannon", "cannons"), ("rocket", "rockets"), ("robot", "robots"), ("magnet", "magnets"), ("battery", "batteries"),
    ("cable", "cables"), ("wire", "wires"), ("switch", "switches"), ("lantern", "lanterns"), ("torch", "torches"),
    ("drum", "drums"), ("guitar", "guitars"), ("violin", "violins"), ("trumpet", "trumpets"), ("flute", "flutes"),
    ("poem", "poems"), ("novel", "novels"), ("magazine", "magazines"), ("newspaper", "newspapers"), ("envelope", "envelopes"),
    ("stamp", "stamps"), ("parcel", "parcels"), ("package", "packages"), ("crate", "crates"), ("barrel", "barrels"),
    ("jar", "jars"), ("tube", "tubes"), ("pot", "pots"), ("pan", "pans"), ("kettle", "kettles"),
    ("oven", "ovens"), ("fridge", "fridges"), ("freezer", "freezers"), ("towel", "towels"), ("comb", "combs"),
    ("razor", "razors"), ("mattress", "mattresses"), ("fence", "fences"), ("gate", "gates"), ("path", "paths"),
    ("trail", "trails"), ("tunnel", "tunnels"), ("canal", "canals"), ("harbor", "harbors"), ("dock", "docks"),
    ("ferry", "ferries"), ("tractor", "tractors"), ("truck", "trucks"), ("van", "vans"), ("taxi", "taxis"),
    ("wagon", "wagons"), ("sled", "sleds"), ("kite", "kites"), ("balloon", "balloons"), ("puzzle", "puzzles"),
    ("card", "cards"), ("medal", "medals"), ("trophy", "trophies"), ("prize", "prizes"), ("badge", "badges"),
    ("flag", "flags"), ("banner", "banners"), ("poster", "posters"), ("statue", "statues"), ("fountain", "fountains"),
    ("pillar", "pillars"), ("column", "columns"), ("arch", "arches"), ("dome", "domes"), ("temple", "temples"),
    ("palace", "palaces"), ("cottage", "cottages"), ("cabin", "cabins"), ("tent", "tents"), ("hut", "huts"),
    ("barn", "barns"), ("mill", "mills"), ("factory", "factories"), ("office", "offices"), ("bakery", "bakeries"),
    ("pharmacy", "pharmacies"), ("gallery", "galleries"), ("academy", "academies"), ("colony", "colonies"), ("enemy", "enemies"),
    ("army", "armies"), ("navy", "navies"), ("spy", "spies"), ("butterfly", "butterflies"), ("dragonfly", "dragonflies"),
    ("hobby", "hobbies"), ("diary", "diaries"), ("memory", "memories"), ("century", "centuries"), ("injury", "injuries"),
    ("ally", "allies"), ("bully", "bullies"), ("jelly", "jellies"), ("penny", "pennies"), ("daisy", "daisies"),
    ("lily", "lilies"), ("poppy", "poppies"), ("coach", "coaches"), ("patch", "patches"), ("ditch", "ditches"),
    ("witch", "witches"), ("lunch", "lunches"), ("punch", "punches"), ("ranch", "ranches"), ("bush", "bushes"),
    ("flash", "flashes"), ("crash", "crashes"), ("splash", "splashes"), ("leash", "leashes"), ("ash", "ashes"),
    ("mix", "mixes"), ("suffix", "suffixes"), ("prefix", "prefixes"), ("reflex", "reflexes"), ("boss", "bosses"),
    ("kiss", "kisses"), ("mess", "messes"), ("guess", "guesses"), ("pass", "passes"), ("lens", "lenses"),
    ("gas", "gases"), ("bonus", "bonuses"), ("virus", "viruses"), ("campus", "campuses"), ("circus", "circuses"),
    ("walrus", "walruses"), ("quiz", "quizzes"), ("waltz", "waltzes"), ("memo", "memos"), ("logo", "logos"),
    ("solo", "solos"), ("studio", "studios"), ("patio", "patios"), ("casino", "casinos"), ("giraffe", "giraffes"),
    ("cafe", "cafes"), ("gulf", "gulfs"), ("proof", "proofs"), ("reef", "reefs"), ("alumnus", "alumni"),
    ("stimulus", "stimuli"), ("larva", "larvae"), ("vertebra", "vertebrae"), ("axis", "axes"), ("oasis", "oases"),
    ("hypothesis", "hypotheses"), ("diagnosis", "diagnoses"), ("parenthesis", "parentheses"), ("emphasis", "emphases"), ("synopsis", "synopses"),
    ("essay", "essays"), ("alley", "alleys"), ("chimney", "chimneys"), ("jersey", "jerseys"), ("journey", "journeys"),
    ("kidney", "kidneys"), ("turkey", "turkeys"), ("holiday", "holidays"), ("birthday", "birthdays"), ("highway", "highways"),
    ("railway", "railways"), ("delay", "delays"), ("decoy", "decoys"), ("cowboy", "cowboys"), ("guy", "guys"),
]

PAST_TENSE_EXTRA: list[tuple[str, str]] = [
    ("accept", "accepted"), ("add", "added"), ("admit", "admitted"), ("allow", "allowed"), ("answer", "answered"),
    ("appear", "appeared"), ("apply", "applied"), ("argue", "argued"), ("attack", "attacked"), ("attend", "attended"),
    ("avoid", "avoided"), ("borrow", "borrowed"), ("bounce", "bounced"), ("breathe", "breathed"), ("burn", "burned"),
    ("chase", "chased"), ("cheer", "cheered"), ("chew", "chewed"), ("choke", "choked"), ("claim", "claimed"),
    ("collect", "collected"), ("compare", "compared"), ("complain", "complained"), ("complete", "completed"), ("confess", "confessed"),
    ("connect", "connected"), ("consider", "considered"), ("contain", "contained"), ("continue", "continued"), ("count", "counted"),
    ("cover", "covered"), ("crash", "crashed"), ("crawl", "crawled"), ("create", "created"), ("dare", "dared"),
    ("deliver", "delivered"), ("depend", "depended"), ("describe", "described"), ("destroy", "destroyed"), ("develop", "developed"),
    ("disagree", "disagreed"), ("discover", "discovered"), ("divide", "divided"), ("doubt", "doubted"), ("drag", "dragged"),
    ("drown", "drowned"), ("earn", "earned"), ("employ", "employed"), ("encourage", "encouraged"), ("enter", "entered"),
    ("escape", "escaped"), ("examine", "examined"), ("excuse", "excused"), ("exist", "existed"), ("expect", "expected"),
    ("explain", "explained"), ("explode", "exploded"), ("fail", "failed"), ("fear", "feared"), ("fetch", "fetched"),
    ("float", "floated"), ("fold", "folded"), ("form", "formed"), ("gather", "gathered"), ("greet", "greeted"),
    ("grin", "grinned"), ("hammer", "hammered"), ("hate", "hated"), ("heat", "heated"), ("hop", "hopped"),
    ("hover", "hovered"), ("ignore", "ignored"), ("imagine", "imagined"), ("improve", "improved"), ("include", "included"),
    ("increase", "increased"), ("invent", "invented"), ("invite", "invited"), ("jog", "jogged"), ("judge", "judged"),
    ("knock", "knocked"), ("land", "landed"), ("last", "lasted"), ("lift", "lifted"), ("load", "loaded"),
    ("manage", "managed"), ("measure", "measured"), ("melt", "melted"), ("mend", "mended"), ("mix", "mixed"),
    ("name", "named"), ("note", "noted"), ("notice", "noticed"), ("offer", "offered"), ("order", "ordered"),
    ("own", "owned"), ("pack", "packed"), ("park", "parked"), ("perform", "performed"), ("permit", "permitted"),
    ("plant", "planted"), ("point", "pointed"), ("pour", "poured"), ("prefer", "preferred"), ("prepare", "prepared"),
    ("present", "presented"), ("press", "pressed"), ("pretend", "pretended"), ("prevent", "prevented"), ("print", "printed"),
    ("produce", "produced"), ("promise", "promised"), ("protect", "protected"), ("prove", "proved"), ("punish", "punished"),
    ("race", "raced"), ("raise", "raised"), ("receive", "received"), ("refuse", "refused"), ("regret", "regretted"),
    ("relax", "relaxed"), ("remain", "remained"), ("remove", "removed"), ("repair", "repaired"), ("repeat", "repeated"),
    ("reply", "replied"), ("report", "reported"), ("rescue", "rescued"), ("retire", "retired"), ("ruin", "ruined"),
    ("rush", "rushed"), ("scream", "screamed"), ("search", "searched"), ("serve", "served"), ("settle", "settled"),
    ("shave", "shaved"), ("shiver", "shivered"), ("skip", "skipped"), ("slip", "slipped"), ("sneeze", "sneezed"),
    ("sniff", "sniffed"), ("spill", "spilled"), ("spoil", "spoiled"), ("squeeze", "squeezed"), ("stare", "stared"),
    ("step", "stepped"), ("stir", "stirred"), ("suffer", "suffered"), ("suggest", "suggested"), ("supply", "supplied"),
    ("support", "supported"), ("suppose", "supposed"), ("surprise", "surprised"), ("surround", "surrounded"), ("suspect", "suspected"),
    ("tap", "tapped"), ("tease", "teased"), ("thank", "thanked"), ("tip", "tipped"), ("trade", "traded"),
    ("trap", "trapped"), ("travel", "traveled"), ("trip", "tripped"), ("trust", "trusted"), ("type", "typed"),
    ("unite", "united"), ("vanish", "vanished"), ("wander", "wandered"), ("warn", "warned"), ("waste", "wasted"),
    ("wave", "waved"), ("weigh", "weighed"), ("whisper", "whispered"), ("wonder", "wondered"), ("wrap", "wrapped"),
    ("yawn", "yawned"), ("zip", "zipped"), ("bet", "bet"), ("bid", "bid"), ("broadcast", "broadcast"),
    ("cast", "cast"), ("quit", "quit"), ("split", "split"), ("thrust", "thrust"), ("upset", "upset"),
    ("kneel", "knelt"), ("lean", "leaned"), ("sew", "sewed"), ("sow", "sowed"), ("saw", "sawed"),
    ("foresee", "foresaw"), ("foretell", "foretold"), ("overthrow", "overthrew"), ("override", "overrode"), ("rewrite", "rewrote"),
    ("undo", "undid"), ("unwind", "unwound"), ("uphold", "upheld"), ("withstand", "withstood"), ("withhold", "withheld"),
    ("mislead", "misled"), ("misunderstand", "misunderstood"), ("outgrow", "outgrew"), ("outrun", "outran"), ("overhear", "overheard"),
    ("oversleep", "overslept"), ("partake", "partook"), ("resell", "resold"), ("retell", "retold"), ("rethink", "rethought"),
    ("slay", "slew"), ("stride", "strode"), ("forsake", "forsook"), ("shed", "shed"),
]

EN_FR_EXTRA: list[tuple[str, str]] = [
    ("to think", "penser"), ("to find", "trouver"), ("to say", "dire"), ("to make", "faire"), ("to leave", "partir"),
    ("to enter", "entrer"), ("to wait", "attendre"), ("to lose", "perdre"), ("to win", "gagner"), ("to hold", "tenir"),
    ("to fall", "tomber"), ("to laugh", "rire"), ("to cry", "pleurer"), ("to forget", "oublier"), ("to help", "aider"),
    ("to live", "vivre"), ("to die", "mourir"), ("to send", "envoyer"), ("to receive", "recevoir"), ("to wash", "laver"),
    ("to swim", "nager"), ("to fly", "voler"), ("to jump", "sauter"), ("to push", "pousser"), ("to pull", "tirer"),
    ("to break", "casser"), ("to build", "construire"), ("to choose", "choisir"), ("to finish", "finir"), ("to begin", "commencer"),
    ("to understand", "comprendre"), ("to believe", "croire"), ("to hope", "espérer"), ("to answer", "répondre"), ("to ask", "demander"),
    ("to bring", "apporter"), ("to carry", "porter"), ("to follow", "suivre"), ("to drive", "conduire"), ("to draw", "dessiner"),
    ("to count", "compter"), ("to pay", "payer"), ("to cost", "coûter"), ("to travel", "voyager"), ("to arrive", "arriver"),
    ("wall", "mur"), ("floor", "sol"), ("roof", "toit"), ("stairs", "escalier"), ("mirror", "miroir"),
    ("clock", "horloge"), ("lamp", "lampe"), ("sofa", "canapé"), ("carpet", "tapis"), ("pillow", "oreiller"),
    ("blanket", "couverture"), ("towel", "serviette"), ("soap", "savon"), ("needle", "aiguille"), ("umbrella", "parapluie"),
    ("glasses", "lunettes"), ("ring", "bague"), ("necklace", "collier"), ("belt", "ceinture"), ("pocket", "poche"),
    ("button", "bouton"), ("wool", "laine"), ("cotton", "coton"), ("leather", "cuir"), ("wood", "bois"),
    ("iron", "fer"), ("sand", "sable"), ("mud", "boue"), ("dust", "poussière"), ("smoke", "fumée"),
    ("ice", "glace"), ("storm", "tempête"), ("cloud", "nuage"), ("thunder", "tonnerre"), ("lightning", "éclair"),
    ("rainbow", "arc-en-ciel"), ("flood", "inondation"), ("drought", "sécheresse"), ("hill", "colline"), ("valley", "vallée"),
    ("field", "champ"), ("meadow", "prairie"), ("path", "chemin"), ("tower", "tour"), ("library", "bibliothèque"),
    ("museum", "musée"), ("theater", "théâtre"), ("cinema", "cinéma"), ("hotel", "hôtel"), ("airport", "aéroport"),
    ("station", "gare"), ("subway", "métro"), ("ship", "navire"), ("wheel", "roue"), ("engine", "moteur"),
    ("tire", "pneu"), ("seat", "siège"), ("duck", "canard"), ("goose", "oie"), ("turkey", "dinde"),
    ("donkey", "âne"), ("goat", "chèvre"), ("monkey", "singe"), ("elephant", "éléphant"), ("giraffe", "girafe"),
    ("snake", "serpent"), ("frog", "grenouille"), ("turtle", "tortue"), ("butterfly", "papillon"), ("bee", "abeille"),
    ("ant", "fourmi"), ("spider", "araignée"), ("fly", "mouche"), ("worm", "ver"), ("shark", "requin"),
    ("whale", "baleine"), ("dolphin", "dauphin"), ("eagle", "aigle"), ("owl", "hibou"), ("swan", "cygne"),
    ("fox", "renard"), ("deer", "cerf"), ("squirrel", "écureuil"), ("hedgehog", "hérisson"), ("bat", "chauve-souris"),
    ("leg", "jambe"), ("knee", "genou"), ("shoulder", "épaule"), ("elbow", "coude"), ("finger", "doigt"),
    ("thumb", "pouce"), ("neck", "cou"), ("back", "dos"), ("stomach", "estomac"), ("skin", "peau"),
    ("blood", "sang"), ("bone", "os"), ("brain", "cerveau"), ("lung", "poumon"), ("tongue", "langue"),
    ("lip", "lèvre"), ("beard", "barbe"), ("ear", "oreille"), ("face", "visage"), ("voice", "voix"),
    ("neighbor", "voisin"), ("stranger", "étranger"), ("enemy", "ennemi"), ("guest", "invité"), ("boss", "patron"),
    ("worker", "ouvrier"), ("writer", "écrivain"), ("painter", "peintre"), ("singer", "chanteur"), ("actor", "acteur"),
    ("baker", "boulanger"), ("butcher", "boucher"), ("thief", "voleur"), ("judge", "juge"), ("lawyer", "avocat"),
    ("engineer", "ingénieur"), ("scientist", "scientifique"), ("heavy", "lourd"), ("empty", "vide"), ("full", "plein"),
    ("clean", "propre"), ("dirty", "sale"), ("wet", "mouillé"), ("dry", "sec"), ("soft", "doux"),
    ("hard", "dur"), ("sweet", "sucré"), ("salty", "salé"), ("bitter", "amer"), ("sour", "aigre"),
    ("dark", "sombre"), ("early", "tôt"), ("late", "tard"), ("near", "près"), ("far", "loin"),
    ("easy", "facile"), ("difficult", "difficile"), ("expensive", "cher"), ("free", "libre"), ("busy", "occupé"),
    ("tired", "fatigué"), ("sick", "malade"), ("wide", "large"), ("narrow", "étroit"), ("deep", "profond"),
    ("thick", "épais"), ("thin", "mince"), ("true", "vrai"), ("false", "faux"), ("same", "même"),
    ("other", "autre"), ("first", "premier"), ("last", "dernier"), ("next", "prochain"), ("eleven", "onze"),
    ("twelve", "douze"), ("thirteen", "treize"), ("fourteen", "quatorze"), ("fifteen", "quinze"), ("sixteen", "seize"),
    ("seventeen", "dix-sept"), ("eighteen", "dix-huit"), ("nineteen", "dix-neuf"), ("twenty", "vingt"), ("thirty", "trente"),
    ("forty", "quarante"), ("fifty", "cinquante"), ("sixty", "soixante"), ("million", "million"), ("pink", "rose"),
    ("grey", "gris"), ("brown", "marron"), ("purple", "violet"),
]

# Multi-syllable verbs whose final consonant doubles before -ing (American spelling).
PARTICIPLE_DOUBLING: set[str] = {
    "begin", "forget", "admit", "prefer", "regret", "permit", "commit", "refer", "occur", "control",
    "upset", "forbid", "outrun", "overrun", "unwrap", "rewrite",
}
# Verbs whose -ing form is irregular relative to the spelling rules.
PARTICIPLE_EXCEPTIONS: dict[str, str] = {
    "be": "being", "see": "seeing", "flee": "fleeing", "agree": "agreeing", "disagree": "disagreeing",
    "free": "freeing", "foresee": "foreseeing", "dye": "dyeing", "singe": "singeing", "die": "dying",
    "lie": "lying", "tie": "tying", "vie": "vying", "picnic": "picnicking", "panic": "panicking",
    "mimic": "mimicking", "traffic": "trafficking", "hoe": "hoeing", "toe": "toeing", "canoe": "canoeing",
    "age": "aging", "quit": "quitting", "quiz": "quizzing", "bus": "busing", "focus": "focusing",
}
